preload = /usr/share/wallpapers/cachyos-wallpapers/BlueNekoLady.png

wallpaper = DP-1,/usr/share/wallpapers/cachyos-wallpapers/BlueNekoLady.png
wallpaper = HDMI-A-1,/usr/share/wallpapers/cachyos-wallpapers/BlueNekoLady.png
