preload = /home/jplasencia/Pictures/wallpapers/Blue.jpg
preload = /home/jplasencia/Pictures/wallpapers/Red.jpg

wallpaper = DP-1,/home/jplasencia/Pictures/wallpapers/Blue.jpg
wallpaper = HDMI-A-1,/home/jplasencia/Pictures/wallpapers/Red.jpg
